export enum OpCode {
    NoOp = '.noop',
    Assign = '.set.var',
    CompareEqual = ".compare.eq",
    Print = '.print',
    LoadString = '.load.str',
    NewInstance = '.new',
    ParseCommand = '.parse.cmd',
    HandleCommand = '.handle.cmd',
    ReadInput = '.read.in',
    GoTo = '.br',
    Return = '.ret',
    BranchRelative = '.br.rel',
    BranchRelativeIfFalse = '.br.rel.false',
    Concatenate = '.concat',
    LoadNumber = '.load.num',
    LoadField = '.load.fld',
    LoadProperty = '.load.prop',
    LoadInstance = '.load.inst',
    LoadLocal = '.load.loc',
    LoadThis = '.load.this',
    InstanceCall = '.call.inst',
    StaticCall = '.call.static',
    ExternalCall = '.call.extern',
    TypeOf = '.typeof',
    InvokeDelegate = '.call.func',
    LoadBoolean = ".load.bool"
}