// WARNING: This file is autogenerated, do not edit manually!
export function getExampleLibraryCode(){
    return "a Container is a kind of decoration.\n" + 
"it is described as \"It's a container.\".\n" + 
"when it is opened:\n" + 
"    if it is \"opened\" then\n" + 
"        say \"It's already open.\";\n" + 
"        abort event;\n" + 
"    and then continue;\n" + 
"and then stop.\n" + 
"when it is closed:\n" + 
"    if it is \"closed\" then\n" + 
"        say \"It's already closed.\";\n" + 
"        abort event;\n" + 
"    and then continue;\n" + 
"and then stop.\n" + 
"\n" + 
"a Chest is a kind of Container.\n" + 
"it is described as \"The chest looks very heavy.\".\n" + 
"it is observed as \"A large chest sits in the corner.\".\n" + 
"it contains 1 to 10 Coin.\n" + 
"when it is opened:\n" + 
"    if it is \"locked\" then\n" + 
"        say \"The lid won't budge.\";\n" + 
"        abort event;\n" + 
"    or else\n" + 
"        say \"The lid creaks with the effort.\";\n" + 
"    and then continue;\n" + 
"and then stop.\n" + 
"when it is closed:\n" + 
"    say \"The lid slams closed.\";\n" + 
"and then stop.\n" + 
"when it is used with a Key:\n" + 
"    if it is \"opened\" then\n" + 
"        say \"You can't lock it when it's open.\";\n" + 
"        abort event;\n" + 
"    and then continue;\n" + 
"    say \"The key turns easily in the lock.\";\n" + 
"    if it is \"locked\" then\n" + 
"        set it to not \"locked\";\n" + 
"    or else\n" + 
"        set it to \"locked\";\n" + 
"    and then continue;\n" + 
"and then stop.\n" + 
"\n" + 
"a Key is a kind of item.\n" + 
"it is described as \"The key is small but sturdy.\".\n" + 
"\n";
}

export function getExampleStoryCode(){
    return "say \"This is the start.\".\n" + 
"\n" + 
"understand \"look\" as describing. \n" + 
"understand \"north\", \"n\" as directions. \n" + 
"understand \"south\" as directions.\n" + 
"understand \"go\" as moving. \n" + 
"understand \"take\" as taking. \n" + 
"understand \"give\" as giving.\n" + 
"understand \"inv\", \"i\" as inventory. \n" + 
"understand \"drop\" as dropping. \n" + 
"understand \"use\" as using.\n" + 
"understand \"open\" as opening.\n" + 
"understand \"close\" as closing.\n" + 
"understand \"combine\" as combining.\n" + 
"understand \"locked\" as stateful.\n" + 
"understand \"Q\" as options.\n" + 
"\n" + 
"when the player presses \"Q\":\n" + 
"    show MainMenu;\n" + 
"and then stop.\n" + 
"\n" + 
"an Inn is a kind of place. \n" + 
"it is where the player starts. \n" + 
"it is described as \"The inn is a cozy place, with a crackling fire on the hearth. An open door to the north leads outside.\" \n" + 
"    and if it contains 1 Key then \"There's a key hanging on the wall.\";\n" + 
"    or else \"There's an empty spot where a key once hung.\";\n" + 
"and then continue.\n" + 
"it contains 1 Fireplace, 1 Chest, 1 Key, 1 Crystal, 1 Bartender.\n" + 
"it can reach the Walkway by going \"north\", \"n\". \n" + 
"it has a value called hasWaved that is false. \n" + 
"when the player exits: \n" + 
"    if hasWaved is false then \n" + 
"        say \"The bartender waves goodbye.\"; \n" + 
"    or else \n" + 
"        say \"The bartender cleans the bar.\"; \n" + 
"    and then continue;\n" + 
"    set hasWaved to true; \n" + 
"and then stop. \n" + 
"\n" + 
"a Crystal is a kind of decoration.\n" + 
"it is described as \"The crystal glows with a soft inner light. It has a small slot for a coin.\".\n" + 
"it is observed as \"A small crystal rests on the bar.\".\n" + 
"when it is combined with a Coin:\n" + 
"    say \"The coin fits neatly into the crystal.\";\n" + 
"    replace it, Coin with CoinCrystal;\n" + 
"and then stop.\n" + 
"\n" + 
"a Fireplace is a kind of decoration. \n" + 
"it is described as \"The fireplace crackles. It's full of fire.\".\n" + 
"when it is used with a Coin:\n" + 
"    say \"The firelight flickers on the surface of the coin.\";\n" + 
"and then stop.\n" + 
"\n" + 
"a Walkway is a kind of place. \n" + 
"it is described as \"The walkway in front of the inn is empty, just a cobblestone entrance. The inn is to the south.\". \n" + 
"it can reach the Inn by going \"south\". \n" + 
"when the player enters:\n" + 
"    say \"You walk onto the cobblestones. They're nice, if you like that sort of thing.\"; \n" + 
"    say \"There's nobody around. The wind whistles a little bit.\"; \n" + 
"and then stop. \n" + 
"\n" + 
"say \"This is the middle.\".\n" + 
"\n" + 
"a Coin is a kind of item. \n" + 
"it is described as \"It's a small coin.\".\n" + 
"it is observed as \"You see a coin.\".\n" + 
"when it is taken:\n" + 
"    say \"You got a coin!\";\n" + 
"and then stop.\n" + 
"when it is dropped:\n" + 
"    say \"You put the coin down!\";\n" + 
"and then stop.\n" + 
"when it is combined:\n" + 
"    say \"You combined the coin!\";\n" + 
"and then stop.\n" + 
"when it is used:\n" + 
"    say \"You used the coin somehow!\";\n" + 
"and then stop.\n" + 
"\n" + 
"a CoinCrystal is a kind of decoration.\n" + 
"it is described as \"It's a crystal with a coin embedded in it.\".\n" + 
"it is observed as \"A crystal with a coin in it lays on the bar.\".\n" + 
"\n" + 
"a Bartender is a kind of creature.\n" + 
"it is described as \"He's smiling and whistling a tune.\".\n" + 
"it is observed as \"A portly gentleman is behind the bar. He looks up as you come in.\".\n" + 
"it is also known as a \"man\", \"gentleman\".\n" + 
"when it is given a Coin:\n" + 
"    say \"The bartender takes the coin and thanks you!\";\n" + 
"and then stop.\n" + 
"\n" + 
"a MainMenu is a kind of menu.\n" + 
"it is described as \"Main Menu\".\n" + 
"it contains options BackOption, QuitOption.\n" + 
"it has a value called numberOfTimesShown that is 0.\n" + 
"when it is described:\n" + 
"    say \"\";\n" + 
"    if numberOfTimesShown is 0 then\n" + 
"        say \"Please select an option by its number.\";\n" + 
"    or else\n" + 
"        say \"Please select an option.\";\n" + 
"    and then continue;\n" + 
"    add 1 to numberOfTimesShown;\n" + 
"and then stop.\n" + 
"when option QuitOption is selected:\n" + 
"    say \"Goodbye.\";\n" + 
"    hide this;\n" + 
"    quit;\n" + 
"and then stop.\n" + 
"when option BackOption is selected:\n" + 
"    say \"Back to the game.\";\n" + 
"    hide this;\n" + 
"and then stop.\n" + 
"\n" + 
"a BackOption is a kind of option.\n" + 
"it is described as \"1) Back\".\n" + 
"\n" + 
"a QuitOption is a kind of option.\n" + 
"it is described as \"2) Quit\".\n" + 
"\n" + 
"say \"This is the end.\".\n";
}